from typing import Final
from netaddr import IPNetwork

COUNTRY_CODE_TO_NAME: Final[dict[str, str]] = {
    "AF": "Afghanistan", "AL": "Albania", "DZ": "Algeria",
    "AS": "American Samoa", "AD": "Andorra", "AO": "Angola", "AI": "Anguilla",
    "AQ": "Antarctica", "AG": "Antigua and Barbuda", "AR": "Argentina",
    "AM": "Armenia", "AW": "Aruba", "AU": "Australia", "AT": "Austria",
    "AZ": "Azerbaijan", "BS": "Bahamas", "BH": "Bahrain", "BD": "Bangladesh",
    "BB": "Barbados", "BY": "Belarus", "BE": "Belgium", "BZ": "Belize",
    "BJ": "Benin", "BM": "Bermuda", "BT": "Bhutan", "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina", "BW": "Botswana", "BV": "Bouvet Island",
    "BR": "Brazil", "IO": "British Indian Ocean Territory",
    "VG": "British Virgin Islands", "BN": "Brunei", "BG": "Bulgaria",
    "BF": "Burkina Faso", "BI": "Burundi", "KH": "Cambodia", "CM": "Cameroon",
    "CA": "Canada", "CV": "Cape Verde", "KY": "Cayman Islands",
    "CF": "Central African Republic", "TD": "Chad", "CL": "Chile",
    "CN": "China", "CX": "Christmas Island", "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia", "KM": "Comoros", "CK": "Cook Islands", "CR": "Costa Rica",
    "HR": "Croatia", "CU": "Cuba", "CY": "Cyprus", "CZ": "Czech Republic",
    "CD": "Democratic Republic of the Congo", "DK": "Denmark", "DJ": "Djibouti",
    "DM": "Dominica", "DO": "Dominican Republic", "TL": "East Timor",
    "EC": "Ecuador", "EG": "Egypt", "SV": "El Salvador",
    "GQ": "Equatorial Guinea", "ER": "Eritrea", "EE": "Estonia",
    "ET": "Ethiopia", "FK": "Falkland Islands", "FO": "Faroe Islands",
    "FJ": "Fiji", "FI": "Finland", "FR": "France", "GF": "French Guiana",
    "PF": "French Polynesia", "TF": "French Southern Territories",
    "GA": "Gabon", "GM": "Gambia", "GE": "Georgia", "DE": "Germany",
    "GH": "Ghana", "GI": "Gibraltar", "GR": "Greece", "GL": "Greenland",
    "GD": "Grenada", "GP": "Guadeloupe", "GU": "Guam", "GT": "Guatemala",
    "GN": "Guinea", "GW": "Guinea-Bissau", "GY": "Guyana", "HT": "Haiti",
    "HM": "Heard Island and McDonald Islands", "HN": "Honduras",
    "HK": "Hong Kong", "HU": "Hungary", "IS": "Iceland", "IN": "India",
    "ID": "Indonesia", "IR": "Iran", "IQ": "Iraq", "IE": "Ireland",
    "IL": "Israel", "IT": "Italy", "CI": "Ivory Coast", "JM": "Jamaica",
    "JP": "Japan", "JO": "Jordan", "KZ": "Kazakhstan", "KE": "Kenya",
    "KI": "Kiribati", "KW": "Kuwait", "KG": "Kyrgyzstan", "LA": "Laos",
    "LV": "Latvia", "LB": "Lebanon", "LS": "Lesotho", "LR": "Liberia",
    "LY": "Libya", "LI": "Liechtenstein", "LT": "Lithuania", "LU": "Luxembourg",
    "MO": "Macau", "MK": "Macedonia", "MG": "Madagascar", "MW": "Malawi",
    "MY": "Malaysia", "MV": "Maldives", "ML": "Mali", "MT": "Malta",
    "MH": "Marshall Islands", "MQ": "Martinique", "MR": "Mauritania",
    "MU": "Mauritius", "YT": "Mayotte", "MX": "Mexico", "FM": "Micronesia",
    "MD": "Moldova", "MC": "Monaco", "MN": "Mongolia", "ME": "Montenegro",
    "MS": "Montserrat", "MA": "Morocco", "MZ": "Mozambique", "MM": "Myanmar",
    "NA": "Namibia", "NR": "Nauru", "NP": "Nepal", "NL": "Netherlands",
    "AN": "Netherlands Antilles", "NC": "New Caledonia", "NZ": "New Zealand",
    "NI": "Nicaragua", "NE": "Niger", "NG": "Nigeria", "NU": "Niue",
    "NF": "Norfolk Island", "KP": "North Korea",
    "MP": "Northern Mariana Islands", "NO": "Norway", "OM": "Oman",
    "PK": "Pakistan", "PW": "Palau", "PS": "Palestinian Territory",
    "PA": "Panama", "PG": "Papua New Guinea", "PY": "Paraguay", "PE": "Peru",
    "PH": "Philippines", "PN": "Pitcairn", "PL": "Poland", "PT": "Portugal",
    "PR": "Puerto Rico", "QA": "Qatar", "CG": "Republic of the Congo",
    "RE": "Reunion", "RO": "Romania", "RU": "Russia", "RW": "Rwanda",
    "SH": "Saint Helena", "KN": "Saint Kitts and Nevis", "LC": "Saint Lucia",
    "PM": "Saint Pierre and Miquelon", "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa", "SM": "San Marino", "ST": "São Tomé and Príncipe",
    "SA": "Saudi Arabia", "SN": "Senegal", "RS": "Serbia",
    "CS": "Serbia and Montenegro", "SC": "Seychelles", "SL": "Sierra Leone",
    "SG": "Singapore", "SK": "Slovakia", "SI": "Slovenia",
    "SB": "Solomon Islands", "SO": "Somalia", "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands", "KR": "South Korea",
    "ES": "Spain", "LK": "Sri Lanka", "SD": "Sudan", "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen", "SZ": "Swaziland", "SE": "Sweden",
    "CH": "Switzerland", "SY": "Syria", "TW": "Taiwan", "TJ": "Tajikistan",
    "TZ": "Tanzania", "TH": "Thailand", "TG": "Togo", "TK": "Tokelau",
    "TO": "Tonga", "TT": "Trinidad and Tobago", "TN": "Tunisia", "TR": "Turkey",
    "TM": "Turkmenistan", "TC": "Turks and Caicos Islands", "TV": "Tuvalu",
    "VI": "U.S. Virgin Islands", "UG": "Uganda", "UA": "Ukraine",
    "AE": "United Arab Emirates", "GB": "United Kingdom", "US": "United States",
    "UM": "United States Minor Outlying Islands", "UY": "Uruguay",
    "UZ": "Uzbekistan", "VU": "Vanuatu", "VA": "Vatican City",
    "VE": "Venezuela", "VN": "Vietnam", "WF": "Wallis and Futuna",
    "EH": "Western Sahara", "YE": "Yemen", "ZM": "Zambia", "ZW": "Zimbabwe",
}

COUNTRY_TO_CURRENCY_MAP: Final[dict[str, str]] = {
    "AF": "AFN", "AL": "ALL", "DZ": "DZD", "AS": "USD", "AD": "EUR",
    "AO": "AOA", "AI": "XCD", "AQ": "USD", "AG": "XCD", "AR": "ARS",
    "AM": "AMD", "AW": "AWG", "AU": "AUD", "AT": "EUR", "AZ": "AZN",
    "BS": "BSD", "BH": "BHD", "BD": "BDT", "BB": "BBD", "BY": "BYR",
    "BE": "EUR", "BZ": "BZD", "BJ": "XOF", "BM": "BMD", "BT": "BTN",
    "BO": "BOB", "BA": "BAM", "BW": "BWP", "BV": "NOK", "BR": "BRL",
    "IO": "USD", "VG": "USD", "BN": "BND", "BG": "BGN", "BF": "XOF",
    "BI": "BIF", "KH": "KHR", "CM": "XAF", "CA": "CAD", "CV": "CVE",
    "KY": "KYD", "CF": "XAF", "TD": "XAF", "CL": "CLP", "CN": "CNY",
    "CX": "AUD", "CC": "AUD", "CO": "COP", "KM": "KMF", "CK": "NZD",
    "CR": "CRC", "HR": "HRK", "CU": "CUP", "CY": "CYP", "CZ": "CZK",
    "CD": "CDF", "DK": "DKK", "DJ": "DJF", "DM": "XCD", "DO": "DOP",
    "TL": "USD", "EC": "USD", "EG": "EGP", "SV": "SVC", "GQ": "XAF",
    "ER": "ERN", "EE": "EEK", "ET": "ETB", "FK": "FKP", "FO": "DKK",
    "FJ": "FJD", "FI": "EUR", "FR": "EUR", "GF": "EUR", "PF": "XPF",
    "TF": "EUR", "GA": "XAF", "GM": "GMD", "GE": "GEL", "DE": "EUR",
    "GH": "GHC", "GI": "GIP", "GR": "EUR", "GL": "DKK", "GD": "XCD",
    "GP": "EUR", "GU": "USD", "GT": "GTQ", "GN": "GNF", "GW": "XOF",
    "GY": "GYD", "HT": "HTG", "HM": "AUD", "HN": "HNL", "HK": "HKD",
    "HU": "HUF", "IS": "ISK", "IN": "INR", "ID": "IDR", "IR": "IRR",
    "IQ": "IQD", "IE": "EUR", "IL": "ILS", "IT": "EUR", "CI": "XOF",
    "JM": "JMD", "JP": "JPY", "JO": "JOD", "KZ": "KZT", "KE": "KES",
    "KI": "AUD", "KW": "KWD", "KG": "KGS", "LA": "LAK", "LV": "LVL",
    "LB": "LBP", "LS": "LSL", "LR": "LRD", "LY": "LYD", "LI": "CHF",
    "LT": "LTL", "LU": "EUR", "MO": "MOP", "MK": "MKD", "MG": "MGA",
    "MW": "MWK", "MY": "MYR", "MV": "MVR", "ML": "XOF", "MT": "MTL",
    "MH": "USD", "MQ": "EUR", "MR": "MRO", "MU": "MUR", "YT": "EUR",
    "MX": "MXN", "FM": "USD", "MD": "MDL", "MC": "EUR", "MN": "MNT",
    "MS": "XCD", "MA": "MAD", "MZ": "MZN", "MM": "MMK", "NA": "NAD",
    "NR": "AUD", "NP": "NPR", "NL": "EUR", "AN": "ANG", "NC": "XPF",
    "NZ": "NZD", "NI": "NIO", "NE": "XOF", "NG": "NGN", "NU": "NZD",
    "NF": "AUD", "KP": "KPW", "MP": "USD", "NO": "NOK", "OM": "OMR",
    "PK": "PKR", "PW": "USD", "PS": "ILS", "PA": "PAB", "PG": "PGK",
    "PY": "PYG", "PE": "PEN", "PH": "PHP", "PN": "NZD", "PL": "PLN",
    "PT": "EUR", "PR": "USD", "QA": "QAR", "CG": "XAF", "RE": "EUR",
    "RO": "RON", "RU": "RUB", "RW": "RWF", "SH": "SHP", "KN": "XCD",
    "LC": "XCD", "PM": "EUR", "VC": "XCD", "WS": "WST", "SM": "EUR",
    "ST": "STD", "SA": "SAR", "SN": "XOF", "CS": "RSD", "SC": "SCR",
    "SL": "SLL", "SG": "SGD", "SK": "SKK", "SI": "EUR", "SB": "SBD",
    "SO": "SOS", "ZA": "ZAR", "GS": "GBP", "KR": "KRW", "ES": "EUR",
    "LK": "LKR", "SD": "SDD", "SR": "SRD", "SJ": "NOK", "SZ": "SZL",
    "SE": "SEK", "CH": "CHF", "SY": "SYP", "TW": "TWD", "TJ": "TJS",
    "TZ": "TZS", "TH": "THB", "TG": "XOF", "TK": "NZD", "TO": "TOP",
    "TT": "TTD", "TN": "TND", "TR": "TRY", "TM": "TMM", "TC": "USD",
    "TV": "AUD", "VI": "USD", "UG": "UGX", "UA": "UAH", "AE": "AED",
    "GB": "GBP", "US": "USD", "UM": "USD", "UY": "UYU", "UZ": "UZS",
    "VU": "VUV", "VA": "EUR", "VE": "VEF", "VN": "VND", "WF": "XPF",
    "EH": "MAD", "YE": "YER", "ZM": "ZMK", "ZW": "ZWD",
}

EU_COUNTRY_CODES: Final[set[str]] = {
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR",
    "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK",
    "SI", "ES", "SE",
}

COUNTRY_TO_CONTINENT_CODE: Final[dict[str, str]] = {
    "AF": "AS", "DZ": "AF", "AO": "AF", "BJ": "AF", "BW": "AF", "BF": "AF",
    "BI": "AF", "CM": "AF", "CV": "AF", "CF": "AF", "TD": "AF", "KM": "AF",
    "CD": "AF", "DJ": "AF", "EG": "AF", "GQ": "AF", "ER": "AF", "ET": "AF",
    "GA": "AF", "GM": "AF", "GH": "AF", "GN": "AF", "GW": "AF", "CI": "AF",
    "KE": "AF", "LS": "AF", "LR": "AF", "LY": "AF", "MG": "AF", "MW": "AF",
    "ML": "AF", "MR": "AF", "MU": "AF", "MA": "AF", "MZ": "AF", "NA": "AF",
    "NE": "AF", "NG": "AF", "CG": "AF", "RW": "AF", "ST": "AF", "SN": "AF",
    "SC": "AF", "SL": "AF", "SO": "AF", "ZA": "AF", "SD": "AF", "SZ": "AF",
    "TZ": "AF", "TG": "AF", "TN": "AF", "UG": "AF", "EH": "AF", "ZM": "AF",
    "ZW": "AF", "AQ": "AN", "BV": "AN", "TF": "AN", "HM": "AN", "GS": "AN",
    "AM": "AS", "AZ": "AS", "BH": "AS", "BD": "AS", "BT": "AS", "IO": "AS",
    "BN": "AS", "KH": "AS", "CN": "AS", "CX": "AS", "CC": "AS", "GE": "AS",
    "HK": "AS", "IN": "AS", "ID": "AS", "IR": "AS", "IQ": "AS", "IL": "AS",
    "JP": "AS", "JO": "AS", "KZ": "AS", "KW": "AS", "KG": "AS", "LA": "AS",
    "LB": "AS", "MO": "AS", "MY": "AS", "MV": "AS", "MN": "AS", "MM": "AS",
    "NP": "AS", "KP": "AS", "OM": "AS", "PK": "AS", "PS": "AS", "PH": "AS",
    "QA": "AS", "RU": "EU", "SA": "AS", "SG": "AS", "KR": "AS", "LK": "AS",
    "SY": "AS", "TW": "AS", "TJ": "AS", "TH": "AS", "TL": "AS", "TR": "AS",
    "TM": "AS", "AE": "AS", "UZ": "AS", "VN": "AS", "YE": "AS", "AL": "EU",
    "AD": "EU", "AT": "EU", "BY": "EU", "BE": "EU", "BA": "EU", "BG": "EU",
    "HR": "EU", "CY": "EU", "CZ": "EU", "DK": "EU", "EE": "EU", "FI": "EU",
    "FR": "EU", "DE": "EU", "GI": "EU", "GR": "EU", "HU": "EU", "IS": "EU",
    "IE": "EU", "IT": "EU", "LV": "EU", "LI": "EU", "LT": "EU", "LU": "EU",
    "MK": "EU", "MT": "EU", "MD": "EU", "MC": "EU", "ME": "EU", "NL": "EU",
    "NO": "EU", "PL": "EU", "PT": "EU", "RO": "EU", "SM": "EU", "RS": "EU",
    "CS": "EU", "SK": "EU", "SI": "EU", "ES": "EU", "SJ": "EU", "SE": "EU",
    "CH": "EU", "UA": "EU", "GB": "EU", "VA": "EU", "AI": "NA", "AG": "NA",
    "BS": "NA", "BB": "NA", "BZ": "NA", "BM": "NA", "CA": "NA", "KY": "NA",
    "CR": "NA", "CU": "NA", "DM": "NA", "DO": "NA", "SV": "NA", "GL": "NA",
    "GD": "NA", "GP": "NA", "GT": "NA", "HT": "NA", "HN": "NA", "JM": "NA",
    "MQ": "NA", "MX": "NA", "MS": "NA", "AN": "NA", "NI": "NA", "PA": "NA",
    "PR": "NA", "KN": "NA", "LC": "NA", "PM": "NA", "VC": "NA", "TC": "NA",
    "US": "NA", "UM": "NA", "VI": "NA", "AS": "OC", "AU": "OC", "CK": "OC",
    "FJ": "OC", "PF": "OC", "GU": "OC", "KI": "OC", "MH": "OC", "FM": "OC",
    "NR": "OC", "NC": "OC", "NZ": "OC", "NU": "OC", "NF": "OC", "MP": "OC",
    "PW": "OC", "PG": "OC", "PN": "OC", "WS": "OC", "SB": "OC", "TK": "OC",
    "TO": "OC", "TV": "OC", "VU": "OC", "WF": "OC", "AR": "SA", "BO": "SA",
    "BR": "SA", "CL": "SA", "CO": "SA", "EC": "SA", "FK": "SA", "GF": "SA",
    "GY": "SA", "PY": "SA", "PE": "SA", "SR": "SA", "UY": "SA", "VE": "SA",
}

COUNTRY_TO_RIR: Final[dict[str, str]] = {
    country: (
        "ripe" if continent == "EU"
        else "apnic" if continent in ["AS", "OC"]
        else "lacnic" if continent == "SA"
        else "afrinic" if continent == "AF"
        else "arin"
    )
    for country, continent in COUNTRY_TO_CONTINENT_CODE.items()
}

CONTINENT_NAME_TO_CODE: Final[dict[str, str]] = {
    "Africa": "AF", "Antarctica": "AN", "Asia": "AS", "Europe": "EU",
    "North America": "NA", "Oceania": "OC", "South America": "SA",
}

PGEOCODE_SUPPORTED_COUNTRY_CODES: Final[list[str]] = [
    "AD", "AR", "AS", "AT", "AU", "AX", "AZ", "BD", "BE", "BG", "BM", "BR",
    "BY", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "DZ",
    "EE", "ES", "FI", "FM", "FO", "FR", "GB", "GF", "GG", "GL", "GP", "GT",
    "GU", "HR", "HT", "HU", "IE", "IM", "IN", "IS", "IT", "JE", "JP", "KR",
    "LI", "LK", "LT", "LU", "LV", "MC", "MD", "MH", "MK", "MP", "MQ", "MT",
    "MW", "MX", "MY", "NC", "NL", "NO", "NZ", "PE", "PH", "PK", "PL", "PM",
    "PR", "PT", "PW", "RE", "RO", "RS", "RU", "SE", "SG", "SI", "SJ", "SK",
    "SM", "TH", "TR", "UA", "US", "UY", "VA", "VI", "WF", "YT", "ZA",
]

KNOWN_NETWORKS: dict[str, dict[str, str]] = {
    # Cloudflare
    "1.1.1.0/24": {
        "org": "Cloudflare, Inc.",
        "domain": "cloudflare.com",
        "abuse_contact": "abuse@cloudflare.com",
        "isp": "Cloudflare",
        "date_allocated": "2018-04-01",
    },
    "1.0.0.0/24": {
        "org": "APNIC Research and Development",
        "domain": "apnic.net",
        "abuse_contact": "helpdesk@apnic.net",
        "isp": "Cloudflare",
        "date_allocated": "2010-01-15",
    },
    "104.16.0.0/12": {
        "org": "Cloudflare, Inc.",
        "domain": "cloudflare.com",
        "abuse_contact": "abuse@cloudflare.com",
        "isp": "Cloudflare",
        "date_allocated": "2014-07-14",
    },
    "2606:4700::/32": {
        "org": "Cloudflare, Inc.",
        "domain": "cloudflare.com",
        "abuse_contact": "abuse@cloudflare.com",
        "isp": "Cloudflare",
        "date_allocated": "2012-08-24",
    },
    # Google
    "8.8.8.0/24": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2009-12-05",
    },
    "8.8.4.0/24": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2009-12-05",
    },
    "34.0.0.0/8": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2012-10-23",
    },
    "35.190.0.0/16": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2015-01-22",
    },
    "35.191.0.0/16": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2015-01-22",
    },
    "66.102.0.0/20": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2000-11-30",
    },
    "108.177.0.0/17": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2011-05-15",
    },
    "172.217.0.0/16": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2012-04-18",
    },
    "2607:f8b0::/32": {
        "org": "Google LLC",
        "domain": "google.com",
        "abuse_contact": "network-abuse@google.com",
        "isp": "Google",
        "date_allocated": "2008-03-22",
    },
    # Amazon AWS
    "3.0.0.0/8": {
        "org": "Amazon Web Services",
        "domain": "aws.amazon.com",
        "abuse_contact": "abuse@amazonaws.com",
        "isp": "Amazon",
        "date_allocated": "2017-07-08",
    },
    "18.32.0.0/11": {
        "org": "Amazon Web Services",
        "domain": "aws.amazon.com",
        "abuse_contact": "abuse@amazonaws.com",
        "isp": "Amazon",
        "date_allocated": "2016-09-27",
    },
    "52.0.0.0/8": {
        "org": "Amazon Web Services",
        "domain": "aws.amazon.com",
        "abuse_contact": "abuse@amazonaws.com",
        "isp": "Amazon",
        "date_allocated": "2014-11-11",
    },
    "54.0.0.0/8": {
        "org": "Amazon Web Services",
        "domain": "aws.amazon.com",
        "abuse_contact": "abuse@amazonaws.com",
        "isp": "Amazon",
        "date_allocated": "2012-07-25",
    },
    "2600:1f00::/24": {
        "org": "Amazon Web Services",
        "domain": "aws.amazon.com",
        "abuse_contact": "abuse@amazonaws.com",
        "isp": "Amazon",
        "date_allocated": "2016-11-10",
    },
    # Microsoft Azure
    "13.64.0.0/11": {
        "org": "Microsoft Corporation",
        "domain": "azure.microsoft.com",
        "abuse_contact": "abuse@microsoft.com",
        "isp": "Microsoft",
        "date_allocated": "2015-09-16",
    },
    "20.0.0.0/8": {
        "org": "Microsoft Corporation",
        "domain": "azure.microsoft.com",
        "abuse_contact": "abuse@microsoft.com",
        "isp": "Microsoft",
        "date_allocated": "2017-12-12",
    },
    "40.64.0.0/10": {
        "org": "Microsoft Corporation",
        "domain": "azure.microsoft.com",
        "abuse_contact": "abuse@microsoft.com",
        "isp": "Microsoft",
        "date_allocated": "2014-05-29",
    },
    "104.208.0.0/13": {
        "org": "Microsoft Corporation",
        "domain": "azure.microsoft.com",
        "abuse_contact": "abuse@microsoft.com",
        "isp": "Microsoft",
        "date_allocated": "2015-01-20",
    },
    "2603:1000::/24": {
        "org": "Microsoft Corporation",
        "domain": "azure.microsoft.com",
        "abuse_contact": "abuse@microsoft.com",
        "isp": "Microsoft",
        "date_allocated": "2014-10-15",
    },
    # Facebook
    "31.13.24.0/21": {
        "org": "Meta Platforms, Inc.",
        "domain": "facebook.com",
        "abuse_contact": "abuse@facebook.com",
        "isp": "Facebook",
        "date_allocated": "2011-10-28",
    },
    "66.220.144.0/20": {
        "org": "Meta Platforms, Inc.",
        "domain": "facebook.com",
        "abuse_contact": "abuse@facebook.com",
        "isp": "Facebook",
        "date_allocated": "2007-06-14",
    },
    "69.63.176.0/20": {
        "org": "Meta Platforms, Inc.",
        "domain": "facebook.com",
        "abuse_contact": "abuse@facebook.com",
        "isp": "Facebook",
        "date_allocated": "2006-05-08",
    },
    "157.240.0.0/16": {
        "org": "Meta Platforms, Inc.",
        "domain": "facebook.com",
        "abuse_contact": "abuse@facebook.com",
        "isp": "Facebook",
        "date_allocated": "2015-08-11",
    },
    "2a03:2880::/32": {
        "org": "Meta Platforms, Inc.",
        "domain": "facebook.com",
        "abuse_contact": "abuse@facebook.com",
        "isp": "Facebook",
        "date_allocated": "2010-08-18",
    },
    # Apple
    "17.0.0.0/8": {
        "org": "Apple Inc.",
        "domain": "apple.com",
        "abuse_contact": "abuse@apple.com",
        "isp": "Apple",
        "date_allocated": "1990-01-01",
    },
    "2620:149::/32": {
        "org": "Apple Inc.",
        "domain": "apple.com",
        "abuse_contact": "abuse@apple.com",
        "isp": "Apple",
        "date_allocated": "2011-09-14",
    },
    # Comcast
    "73.0.0.0/8": {
        "org": "Comcast Cable Communications",
        "domain": "comcast.net",
        "abuse_contact": "abuse@comcast.net",
        "isp": "Comcast",
        "date_allocated": "2013-11-22",
    },
    "76.96.0.0/12": {
        "org": "Comcast Cable Communications",
        "domain": "comcast.net",
        "abuse_contact": "abuse@comcast.net",
        "isp": "Comcast",
        "date_allocated": "2006-08-18",
    },
    "2601::/20": {
        "org": "Comcast Cable Communications",
        "domain": "comcast.net",
        "abuse_contact": "abuse@comcast.net",
        "isp": "Comcast",
        "date_allocated": "2012-03-30",
    },
    # Verizon
    "70.0.0.0/8": {
        "org": "Verizon Business",
        "domain": "verizon.com",
        "abuse_contact": "abuse@verizon.net",
        "isp": "Verizon",
        "date_allocated": "2005-07-15",
    },
    "72.0.0.0/8": {
        "org": "Verizon Business",
        "domain": "verizon.com",
        "abuse_contact": "abuse@verizon.net",
        "isp": "Verizon",
        "date_allocated": "2006-01-23",
    },
    "2600:6c00::/24": {
        "org": "Verizon Business",
        "domain": "verizon.com",
        "abuse_contact": "abuse@verizon.net",
        "isp": "Verizon",
        "date_allocated": "2013-06-05",
    },
    # AT&T
    "12.0.0.0/8": {
        "org": "AT&T Services, Inc.",
        "domain": "att.com",
        "abuse_contact": "abuse@att.com",
        "isp": "AT&T",
        "date_allocated": "1989-01-01",
    },
    "67.0.0.0/8": {
        "org": "AT&T Services, Inc.",
        "domain": "att.com",
        "abuse_contact": "abuse@att.com",
        "isp": "AT&T",
        "date_allocated": "2004-06-28",
    },
    "2600:1000::/24": {
        "org": "AT&T Services, Inc.",
        "domain": "att.com",
        "abuse_contact": "abuse@att.com",
        "isp": "AT&T",
        "date_allocated": "2012-09-19",
    },
    # Oracle Cloud
    "130.35.0.0/16": {
        "org": "Oracle Corporation",
        "domain": "oracle.com",
        "abuse_contact": "abuse@oracle.com",
        "isp": "Oracle",
        "date_allocated": "1991-05-22",
    },
    "134.70.0.0/16": {
        "org": "Oracle Corporation",
        "domain": "oracle.com",
        "abuse_contact": "abuse@oracle.com",
        "isp": "Oracle",
        "date_allocated": "1992-03-16",
    },
    "2603:c020::/32": {
        "org": "Oracle Corporation",
        "domain": "oracle.com",
        "abuse_contact": "abuse@oracle.com",
        "isp": "Oracle",
        "date_allocated": "2016-09-21",
    },
    # Akamai
    "23.0.0.0/8": {
        "org": "Akamai Technologies",
        "domain": "akamai.com",
        "abuse_contact": "abuse@akamai.com",
        "isp": "Akamai",
        "date_allocated": "2010-11-15",
    },
    "2600:1400::/24": {
        "org": "Akamai Technologies",
        "domain": "akamai.com",
        "abuse_contact": "abuse@akamai.com",
        "isp": "Akamai",
        "date_allocated": "2012-08-10",
    },
    # IBM Cloud
    "5.10.0.0/16": {
        "org": "IBM Corporation",
        "domain": "ibm.com",
        "abuse_contact": "abuse@ibm.com",
        "isp": "IBM",
        "date_allocated": "2012-04-30",
    },
    "2620:1ae::/32": {
        "org": "IBM Corporation",
        "domain": "ibm.com",
        "abuse_contact": "abuse@ibm.com",
        "isp": "IBM",
        "date_allocated": "2011-07-19",
    },
    # Alibaba Cloud
    "47.52.0.0/16": {
        "org": "Alibaba Group",
        "domain": "alibabacloud.com",
        "abuse_contact": "abuse@alibabacloud.com",
        "isp": "Alibaba Cloud",
        "date_allocated": "2016-02-25",
    },
    "2400:cb00::/32": {
        "org": "Alibaba Group",
        "domain": "alibabacloud.com",
        "abuse_contact": "abuse@alibabacloud.com",
        "isp": "Alibaba Cloud",
        "date_allocated": "2015-10-07",
    },
    # Digital Ocean
    "45.55.0.0/16": {
        "org": "DigitalOcean, LLC",
        "domain": "digitalocean.com",
        "abuse_contact": "abuse@digitalocean.com",
        "isp": "DigitalOcean",
        "date_allocated": "2014-12-18",
    },
    "104.236.0.0/16": {
        "org": "DigitalOcean, LLC",
        "domain": "digitalocean.com",
        "abuse_contact": "abuse@digitalocean.com",
        "isp": "DigitalOcean",
        "date_allocated": "2014-09-05",
    },
    "2604:a880::/32": {
        "org": "DigitalOcean, LLC",
        "domain": "digitalocean.com",
        "abuse_contact": "abuse@digitalocean.com",
        "isp": "DigitalOcean",
        "date_allocated": "2014-08-11",
    },
    # Tencent Cloud
    "43.242.0.0/16": {
        "org": "Tencent Holdings",
        "domain": "tencent.com",
        "abuse_contact": "abuse@tencent.com",
        "isp": "Tencent Cloud",
        "date_allocated": "2013-12-05",
    },
    "111.231.0.0/16": {
        "org": "Tencent Holdings",
        "domain": "tencent.com",
        "abuse_contact": "abuse@tencent.com",
        "isp": "Tencent Cloud",
        "date_allocated": "2017-06-15",
    },
    "2402:4e00::/32": {
        "org": "Tencent Holdings",
        "domain": "tencent.com",
        "abuse_contact": "abuse@tencent.com",
        "isp": "Tencent Cloud",
        "date_allocated": "2014-03-27",
    },
}

NETWORKS: list[tuple[IPNetwork, dict[str, str]]] = [
    (IPNetwork(prefix), data) for prefix, data in KNOWN_NETWORKS.items()
]

VPN_PROVIDERS: Final[list[str]] = [
    "NordVPN", "ProtonVPN", "ExpressVPN", "Surfshark",
    "PrivateInternetAccess", "CyberGhost", "TunnelBear", "Mullvad",
]

TOR_EXIT_NODE_ASNS: Final[list[str]] = [
    "60729", "53667", "4224", "208323", "198093", "401401", "210731", "61125",
    "214503", "215125", "214094", "205100", "57860", "8283", "215659", "197648",
    "44925", "198985", "214996", "210083", "49770", "197422", "205235", "30893",
]

GENERAL_EMAIL_PROVIDERS = {
    "gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "aol.com",
    "icloud.com", "protonmail.com", "mail.com", "yandex.com", "zoho.com",
    "fastmail.com", "tutanota.com", "gmx.com", "web.de", "mail.ru", "qq.com",
    "163.com", "126.com", "sina.com", "sohu.com", "mail.mil",
}
